			ASSUME CS:CODE,DS:CODE
CODE 		SEGMENT
			ORG 100H
main		PROC
			MOV AX,0B800H
			MOV ES,AX
			
M0:			MOV AH,8
			INT 21H
			CMP AL,'D'
			JNE M1
			CALL RIGHT
			JMP	M0
M1:			CMP AL,'Z'
			JNE M2
			CALL DOWN
			JMP M0
M2:			CMP AL,'A'
			JNE M3
			CALL LEFT
			JMP M0
M3:			CMP AL,'W'
			JNE M4
			CALL UP
			JMP M0
M4:			CMP AL,'F'
			JNE M5
			CALL FCOLOR
			JMP M0
M5:			CMP AL,'G'
			JNE M6
			CALL GCOLOR
			JMP M0
M6:			CMP AL,'B'
			JNE M7
			CALL BCOLOR
			JMP M0
M7:			CMP AL,'I'
			JNE M8
			CALL ICOLOR
			JMP M0
M8:			CMP AL,'S'	
			JNE M0
			
M9:			MOV AH,4CH	
			INT 21H		
main		ENDP

RIGHT 		PROC
			CMP WORD PTR DS:[X],78
			JG	R9
			INC WORD PTR DS:[X]
			CALL DRAW
R9:			RET
RIGHT		ENDP

DOWN 		PROC
			CMP WORD PTR DS:[Y],23
			JG	D9
			INC WORD PTR	DS:[Y]
			CALL DRAW
D9:			RET
DOWN 		ENDP

LEFT 		PROC
			CMP WORD PTR DS:[X],1
			JE	L9
			DEC WORD PTR	DS:[X]
			CALL DRAW
L9:			RET
LEFT 		ENDP

UP			PROC
			CMP WORD PTR DS:[Y],0
			JE	U9
			DEC WORD PTR DS:[Y]
			CALL DRAW
U9:			RET
UP			ENDP

FCOLOR		PROC
			CMP WORD PTR DS:[FG],1111b
			JE 	FC1
			INC WORD PTR DS:[FG]
			JMP FC9
FC1:		MOV WORD PTR DS:[FG],0
FC9:		CALL DRAW
			RET
FCOLOR		ENDP

GCOLOR		PROC
			CMP WORD PTR DS:[BG],111B
			JE 	GC1
			INC	WORD PTR DS:[BG]
			JMP GC9
GC1:		MOV WORD PTR DS:[BG],0
GC9:		CALL DRAW
			RET
GCOLOR		ENDP

ICOLOR		PROC
			CMP WORD PTR DS:[INVISIBLE],0
			JE 	IC1
			INC WORD PTR DS:[INVISIBLE]
			JMP IC9
IC1:		MOV WORD PTR DS:[INVISIBLE],1
IC9:		RET
ICOLOR		ENDP

BCOLOR		PROC
			CMP WORD PTR DS:[B],0
			JE 	BC1
			INC WORD PTR DS:[B]
			JMP BC9
BC1:		MOV WORD PTR DS:[B],1
BC9:		RET
BCOLOR		ENDP

DRAW		PROC
			CMP WORD PTR DS:[INVISIBLE],0
			JE 	DR9
			MOV AX,CS:[Y]
			MOV BX,160
			MUL BX
			MOV BX,CS:[X]
			SHL AX,1
			ADD AX,BX
			MOV DI,AX
			
			MOV AL,DS:[BG]
			SHL AL,4		;00000000				IF	00000010
			OR	AL,DS:[FG]	;00000000 OR 00001111		00010000	OR	00101111
			MOV BL,DS:[B]
			SHL BL,7		;00000001	==>	10000000
			OR 	AL,BL		; 										== 10101111
			XCHG AL,AH
			MOV AL,DS:[CHR]
			STOSW
DR9:		RET
DRAW		ENDP
INVISIBLE	DW 	1
X			DW	0
Y			DW	0
FG			DB	0
BG			DB	111B
B			DB	0	
CHR			DB	'B'
CODE		ENDS
			END main